obstacle_range: 2.0
raytrace_range: 2.5
footprint: [[-0.19,0.28],[-0.08,0.28],[0.15,0.24],[0.15,-0.24],[-0.08,-0.28],[-0.19,-0.28],[-0.4,-0.16],[-0.4,0.16]]
inflation_radius: 0.6

cost_scaling_factor: 10.0
observation_sources: laser_scan_sensor
laser_scan_sensor: {sensor_frame: xv11, data_type: LaserScan, topic: /xv11_scan, marking: true, clearing: true, expected_update_rate: 0.4, inf_is_valid: true}
