global_costmap:
   global_frame: /map
   robot_base_frame: /base_footprint
   update_frequency: 2.0
   publish_frequency: 1.0
   static_map: true
   rolling_window: false
   resolution: 0.05
   transform_tolerance: 0.5
   map_type: costmap
